---
title: "Imprint"
toc: false
---

*English version below*
           
## ViSdP

**Angaben gemäß § 5 TMG**

Felix Dietrich,
Institut für Publizistik, 
Jakob-Welder-Weg 12,
55128 Mainz

mail [ät] felix-dietrich.de <a target="_blank" href="https://keys.openpgp.org/search?q=mail%40felix-dietrich.de">(PGP)</a>

## Datenschutzerklärung

Es werden von mir keine personenbezogenen Daten erhoben, gespeichert, ausgewertet oder an Drittanbieter übertragen.

Der Provider dieser Seite erhebt und speichert automatisch Informationen in so genannten Server-Log-Dateien. Diese beinhalten, welche Browser beim Zugriff auf die Website genutzt werden und welche Seiten wie häufig aufgerufen werden. Die IP-Adresse wird anonymisiert. Eine personenbezogene Auswertung dieser Daten ist somit ausgeschlossen.

***

## Privacy Policy

*No personal data is collected, stored, evaluated or transmitted to third-party providers by me.*

*The provider of this site automatically collects and stores information in so-called server log files. These contain which browsers are used when accessing the website and which pages are accessed and how often. The IP address is anonymized. A personal evaluation of this data is therefore not possible*
