---
title: "What constitutes experiences of autonomy in digital technology use?"
subtitle: "A (computational) scoping review through the lens of self-determination theory"
description: "Interacting with Computers"
author:
  - Felix Dietrich
  - Anisha Arenz
  - Leonard Reinecke
date: 2024-11-13
csl: https://www.zotero.org/styles/apa
bibliography: "../../bib/pubs-articles.bib"
nocite: "@dietrichWhatConstitutesExperiences2024"
about:
  id: hero-heading
  template: solana
  links:
    - text: "{{< ai closed-access >}} PDF"
      href: https://doi.org/10.1093/iwc/iwae050
    - text: "{{< ai open-access >}} Postprint (Open Access)"
      href: https://doi.org/10.31219/osf.io/asbzy
    - text: "{{< ai open-data >}} Data"
      href: https://osf.io/t3dpj
    - icon: code
      text: Code
      href: https://felixdidi.github.io/autonomy-review
---

::: {#hero-heading}
:::

The use of digital communication technologies such as social media, mobile phones, instant messaging, or games, has been found to differentially satisfy and frustrate users’ need for autonomy. Consequently, such technology use can have differential and divergent effects, for example on users’ well-being and mental health. Through our (computational) scoping review of a very broad literature base, we find that many different research perspectives are involved in the study of what constitutes need-based experiences of autonomy in digital technology use. To advance the application of self-determination theory in human–computer interaction, communication research, and beyond, we seek to explain the complex relationship of technology use and individuals’ autonomy need experiences by integrating insights from these diverse perspectives. Based on the heterogenous and often weak theoretical basis within the investigated literature, we suggest that future research should differentiate between control as the central technology-centered (i.e. material) component and authenticity as the core user-centered (i.e. experiential) component, which together constitute experiences of autonomy need satisfaction in digital technology use. Furthermore, it should consider relevant contextual and situational boundary conditions, which can be derived from the reviewed literature.
