---
title: "What do people watch under adversity?"
subtitle: "Testing interactions of semantic affinity and coping style using Netflix data donations"
description: "Human Communication Research"
author:
  - Rebekka Kreling
  - Felix Dietrich
  - Alicia Gilbert
  - Leonard Reinecke
date: 2025-09-02
csl: https://www.zotero.org/styles/apa
bibliography: "../../bib/pubs-articles.bib"
nocite: "@krelingWhatPeopleWatch2025"
about:
  id: hero-heading
  template: solana
  links:
    - text: "{{< ai closed-access >}} PDF"
      href: https://doi.org/10.1093/hcr/hqaf019
    - text: "{{< ai open-access >}} Postprint (Open Access)"
      href: https://osf.io/utjre/
    - text: "{{< ai preregistered >}} Preregistration"
      href: https://osf.io/cjdnp/?view_only=c006be400c2f4f6aadf728730479f763
    - text: "{{< ai open-data >}} Data"
      href: https://osf.io/5updj/
    - icon: code
      text: Code
      href: https://osf.io/5updj/
---

::: {#hero-heading}
:::

Media are frequently used for coping with everyday stressors, but little is known about what *content* individuals choose under such adversity. Building on mood management theory’s propositions about semantic affinity of content, we test how adversity in specific life domains is reflected in choice of entertaining media content surrounding the same life domain. In combining diary data from *n* = 122 Netflix users and data donations of their viewing histories with *n* = 2,122 titles, our study provides a novel methodological approach. Our findings show no effects of daily adversity on selecting content with more or less semantic affinity, but exploratory analyses reveal that daily media coping strategies differentially relate to the selection of different entertainment genres. These results emphasize (a) a lack of conceptual clarity surrounding semantic affinity in real-life media use and (b) the importance of situational approaches in media coping research.
